# background_opacity = 0.95

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x181825"
blue = "0x3e5767"
cyan = "0x3e5767"
green = "0x628168"
magenta = "0x734a5f"
red = "0x89556b"
white = "0xcdd6f4"
yellow = "0x766c62"

# [colors.hyperlink]
# foreground = "0x0087bd"
# underline = true

[colors.normal]
black = "0x181825"
blue = "0x3e5767"
cyan = "0x628168"
green = "0x475a51"
magenta = "0x734a5f"
red = "0x5e3f53"
white = "0xa6adc8"
yellow = "0x766c62"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[colors.selection]
background = "0x3e5767"
text = "0xcdd6f4"

[cursor]
style = "Block"
unfocused_hollow = false

[font]
size = 13.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
# hide_timeout = 2.0
hide_when_typing = true
