require("core.keymaps")
require("core.options")
require("pack")

-- vim.cmd("colorscheme github_dark_default")
-- vim.cmd("colorscheme everforest")
-- vim.cmd("colorscheme vscode")
vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme catppuccin")
-- vim.cmd("colorscheme rose-pine")
