background {
    monitor = eDP-1
    path = /home/neo/Pictures/Wallpapers/city-skyline-sunset-car-anime.webp
    blur_size = 4
    blur_passes = 2
    brightness = 0.8
}

input-field {
    monitor = eDP-1
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255,255,255,0.4)
    inner_color = rgba(0,0,0,0.6)
    font_color  = rgba(255,255,255,1)
    fade_on_empty = true
    placeholder_text = Enter your password
    position = 0, -100
    halign = center
    valign = center
}

# الساعة
label {
    monitor = eDP-1
    text = cmd[date +'%H:%M']
    interval = 60
    font_size = 64
    color = rgba(255,255,255,0.9)
    position = 0, -200
    halign = center
    valign = center
}

# التاريخ
label {
    monitor = eDP-1
    text = cmd[date +'%A, %d %B %Y']
    interval = 3600
    font_size = 20
    color = rgba(220,220,220,0.8)
    position = 0, -260
    halign = center
    valign = center
}

# لغة الكيبورد (EN / AR)
label {
    monitor = eDP-1
    text = cmd[hyprctl devices -j | jq -r '.keyboards[0].active_keymap' | awk '{print toupper(substr($1,1,2))}']
    interval = 1
    font_size = 20
    color = rgba(200,200,200,0.9)
    position = 0, -320
    halign = center
    valign = center
}
